import{a as m}from"./assets/vendor-a61d8330.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y=document.querySelector(".list"),u=document.querySelector(".form-search"),i=document.querySelector(".error"),d=document.querySelector("#selected");i.style.display="none";let g,n,c;u.addEventListener("submit",h);function h(t){t.preventDefault();const{search:o}=t.currentTarget.elements;n={keywords:o.value},localStorage.setItem("SaveFilters",JSON.stringify(n.keywords)||null),localStorage.setItem("savetext",n.keywords),p()}u.elements.search.value=localStorage.getItem("savetext");p();d.addEventListener("change",S);function S(t){const o=t.target.value;g=o,console.log(d.value),c={selectedForm:o},localStorage.setItem("SaveCategpries",JSON.stringify(c.selectedForm)||null),localStorage.setItem("saveselected",c.selectedForm),console.log(c.selectedForm),p()}u.elements.selecteds.value=localStorage.getItem("saveselected");async function p(){try{const t=await v();return console.log(t.results),t.results.length===0?i.style.display="block":i.style.display="none",y.innerHTML=w(t.results)}catch(t){console.log(t)}}async function v(t=1,o=6){let s=g||null;const l="https://food-boutique.b.goit.study/api/products";try{const e=await m(`${l}?`,{params:{keyword:JSON.parse(localStorage.getItem("SaveFilters")),category:JSON.parse(localStorage.getItem("SaveCategpries")),page:1,limit:6}});return console.log(s),console.log(e),console.log(e.data),e.data}catch(e){console.log(e)}}async function b(){try{const o=(await f()).map(s=>`<option value="${s}">${s}</option>`).join("");d.insertAdjacentHTML("beforeend",o)}catch(t){console.log(t)}}b();async function f(t=1){try{return(await m("https://food-boutique.b.goit.study/api/products/categories",{params:{category:g}})).data}catch(o){console.log(o)}}f();function w(t){return t.map(({name:o,img:s,category:l,price:e})=>`
        <ul class="list-product">
        <li class="item-product">
        <img class="img-product" src="${s}" width="400" height="200">
        <h2 class="caption-product">${o}</h2>
        <h3>${l}</h3>
        <p class="price-product">Price:${e}</p>
        </li>
        </ul>
        `).join("")}
//# sourceMappingURL=commonHelpers.js.map
