import{a as p}from"./assets/vendor-a61d8330.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const m=document.querySelector(".list"),y=document.querySelector(".form-search"),a=document.querySelector(".error"),i=document.querySelector("#selected");a.style.display="none";let g,u,d;y.addEventListener("submit",h);function h(e){e.preventDefault();const{search:r}=e.currentTarget.elements;u={keywords:r.value},localStorage.setItem("SaveFilters",JSON.stringify(u.keywords)||null),l()}l();i.addEventListener("change",S);function S(e){const r=e.target.value;g=r,console.log(i.value),d={selectedForm:r},localStorage.setItem("SaveCategpries",JSON.stringify(d.selectedForm)||null),l()}async function l(){try{const e=await v();return e.results.length===0?a.style.display="block":a.style.display="none",m.innerHTML=L(e.results)}catch(e){console.log(e)}}async function v(e=1,r=6){const s="https://food-boutique.b.goit.study/api/products";try{return(await p(`${s}?`,{params:{keyword:JSON.parse(localStorage.getItem("SaveFilters")),category:JSON.parse(localStorage.getItem("SaveCategpries")),page:1,limit:6}})).data}catch(c){console.log(c)}}async function b(){try{const r=(await f()).map(s=>`<option value="${s}">${s}</option>`).join("");i.insertAdjacentHTML("beforeend",r)}catch(e){console.log(e)}}b();async function f(e=1){try{return(await p("https://food-boutique.b.goit.study/api/products/categories",{params:{category:g}})).data}catch(r){console.log(r)}}f();function L(e){return e.map(({name:r,img:s,category:c,price:t})=>`
        <ul class="list-product">
        <li class="item-product">
        <img class="img-product" src="${s}" width="400" height="200">
        <h2 class="caption-product">${r}</h2>
        <h3>${c}</h3>
        <p class="price-product">Price:${t}</p>
        </li>
        </ul>
        `).join("")}
//# sourceMappingURL=commonHelpers.js.map
