import{a as u}from"./assets/vendor-a61d8330.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const g=document.querySelector(".list"),m=document.querySelector(".form-search"),d=document.querySelector(".error"),a=document.querySelector("#selected");d.style.display="none";let p,l;m.addEventListener("submit",y);function y(t){t.preventDefault();const{search:o}=t.currentTarget.elements;p=o.value,i()}i();a.addEventListener("change",h);function h(t){l=t.target.value,console.log(a.value),i()}async function i(){try{const t=await b();return console.log(t.results),t.results.length===0&&(d.style.display="block"),g.innerHTML=v(t.results)}catch(t){console.log(t)}}async function b(t=1){const o=p;let c=l;const n="https://food-boutique.b.goit.study/api/products";try{const e=await u(`${n}?`,{params:{keyword:o,category:c,page:2}});return console.log(c),console.log(e),console.log(e.data),e.data}catch(e){console.log(e)}}async function L(){try{const o=(await f()).map(c=>`<option value="${c}">${c}</option>`).join("");a.insertAdjacentHTML("beforeend",o)}catch(t){console.log(t)}}L();async function f(t=1){try{return(await u("https://food-boutique.b.goit.study/api/products/categories",{params:{category:l}})).data}catch(o){console.log(o)}}f();function v(t){return t.map(({name:o,img:c,category:n,price:e})=>`
        <ul class="list-product">
        <li class="item-product">
        <img class="img-product" src="${c}" width="400" height="200">
        <h2 class="caption-product">${o}</h2>
        <h3>${n}</h3>
        <p class="price-product">Price:${e}</p>
        </li>
        </ul>
        `).join("")}
//# sourceMappingURL=commonHelpers.js.map
